name: triggercompatibility

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        default: true
        type: boolean
      logLevelS:
        required: true
        default: hello
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print output
      run: echo "Hello world logLevel!  ${{ inputs.logLevel }}"
