name: triggercompatibility

on: 
  workflow_dispatch:
    inputs:
      logLevelB:
        type: boolean
        default: true
      logLevelS:
        type: string
        default: mlcb
      logLevelN:
        type: number
        default: 666
      logLevelC:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt3
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print output
      run: echo "Hello world logLevelS!  ${{ inputs.logLevelB }} + ${{ inputs.logLevelS }}  + ${{ inputs.logLevelN }}  + ${{ inputs.logLevelC }}"
