name: triggercompatibility

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        required: false
        type: boolean
      
  push:
  schedule:
    - cron: "13 13 13 12 *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print output
      run: echo "Hello world logLevel!  ${{ inputs.logLevel }}"
